BU:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
  s_layers: 1
Bi:
  a: sca
  a_dim: 512
  a_ffdim: 512
  a_layers: 6
  a_nhead: 8
  dropout: 0.0
  f: m2
  f_dim: 512
  f_layers: 10
  f_ln: false
  f_ngp: 1
  hid_dim: 512
Bu:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
FACT:
  block: iuUU
  cmr: 0.3
  fpos: false
  mwt: 0.1
  ntoken: 526
  trans: false
Loss:
  a2fc: 1.0
  bgw: 1.0
  match: o2o
  nullw: -1.0
  pc: 0.2
  sw: 5.0
TM:
  inplace: true
  m: 5
  p: 0.05
  t: 30
  use: true
aux:
  debug: false
  eval_every: 2000
  gpu: 0
  mark: ''
  print_every: 1000
  resume: max
  runid: 0
average_transcript_len: 149.375
batch_size: 1
bg_class: 0
clip_grad_norm: 10.0
dataset: stanford_binary
num_classes: 2
epoch: 150
eval_bg: true
feature_path: /data-8tb/nvaci/dataset/dataset_Stanford/FACT_method/preprocessed_data_2class_originalFPS/features
feature_transpose: false
groundTruth_path: /data-8tb/nvaci/dataset/dataset_Stanford/FACT_method/preprocessed_data_2class_originalFPS/groundTruth
lr: 0.0001
lr_decay: 80
map_fname: /data-8tb/nvaci/dataset/dataset_Stanford/FACT_method/preprocessed_data_2class_originalFPS/mapping.txt
momentum: 0.0
optimizer: Adam
split: split1
split_path: /data-8tb/nvaci/dataset/dataset_Stanford/FACT_method/preprocessed_data_2class_originalFPS/splits
sr: 1
weight_decay: 0.0
